# action.yml
name: 'Build STM32CubeIde project'
description: 'Build the selected target in an STM32CubeIde project'
inputs:
  project-path:  # id of input
    description: 'Path to STM32CubeIde project'
    required: true
  project-target:  # id of input
    description: 'Which target in the STM32CubeIde project to build. Format: target/[build-configuration]'
    required: true
  additional-defines:
    description: 'Newline-delimited list of additional preprocessor defines to be set during build.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-path }}
    - ${{ inputs.project-target }}
    - "${{ inputs.additional-defines }}"
